/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef BACKEND_ADAPTOR_H
#define BACKEND_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface de.rwth.iss.oop
 */
class OopAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "de.rwth.iss.oop")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"de.rwth.iss.oop\">\n"
"    <signal name=\"sendPixelRow\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"row\"/>\n"
"      <arg direction=\"out\" type=\"ab\" name=\"pixelrow\"/>\n"
"      <annotation value=\"QList&lt;bool&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out1\"/>\n"
"    </signal>\n"
"    <signal name=\"receivePixelRow\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"row\"/>\n"
"      <arg direction=\"out\" type=\"ab\" name=\"pixelrow\"/>\n"
"      <annotation value=\"QList&lt;bool&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out1\"/>\n"
"      <arg direction=\"out\" type=\"d\" name=\"ber\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"flag\"/>\n"
"    </signal>\n"
"    <signal name=\"configCRC\">\n"
"      <arg direction=\"out\" type=\"ab\" name=\"poly\"/>\n"
"      <annotation value=\"QList&lt;bool&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </signal>\n"
"    <signal name=\"configECC\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"factor\"/>\n"
"    </signal>\n"
"    <signal name=\"configMapping\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"map\"/>\n"
"    </signal>\n"
"    <signal name=\"configSNR\">\n"
"      <arg direction=\"out\" type=\"d\" name=\"snr\"/>\n"
"    </signal>\n"
"    <signal name=\"frontendStatus\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"present\"/>\n"
"    </signal>\n"
"    <signal name=\"backendStatus\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"present\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    OopAdaptor(QObject *parent);
    virtual ~OopAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void backendStatus(bool present);
    void configCRC(const QList<bool> &poly);
    void configECC(int factor);
    void configMapping(int map);
    void configSNR(double snr);
    void frontendStatus(bool present);
    void receivePixelRow(int row, const QList<bool> &pixelrow, double ber, bool flag);
    void sendPixelRow(int row, const QList<bool> &pixelrow);
};

#endif
