/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OOP_INTERFACE_H
#define OOP_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface de.rwth.iss.oop
 */
class DeRwthIssOopInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "de.rwth.iss.oop"; }

public:
    DeRwthIssOopInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DeRwthIssOopInterface();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void backendStatus(bool present);
    void configCRC(const QList<bool> &poly);
    void configECC(int factor);
    void configMapping(int map);
    void configSNR(double snr);
    void frontendStatus(bool present);
    void receivePixelRow(int row, const QList<bool> &pixelrow, double ber, bool flag);
    void sendPixelRow(int row, const QList<bool> &pixelrow);
};

namespace de {
  namespace rwth {
    namespace iss {
      typedef ::DeRwthIssOopInterface oop;
    }
  }
}
#endif
